### ISSUE TITLE
Automate branch creation?

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-setup#11]
Given that the ideal branch set-up is as follows...

- `master` for production ready code
- `staging` for QA/testing/client review
- `develop` for ongoing development

...should the script provide the option to create the default branches for us and then take care of the necessary downstream/upstream links?

Needs some discussion, but very simple and quick to implement.

**Comment by mwtsn** [comment]
@davetgreen talked about this offline, and it should create the repo and the branches :)

**Comment by mwtsn** [comment]
```
# Create the GitHub Repo
curl -u 'your_username' https://api.github.com/orgs/mkdo/repos -d '{"name":"your-website","private":"true"}'
```

**Comment by davetgreen** [comment]
Completed. The script now is now capable of creating a repository and adding the additional default `staging` and `develop` branches.
