### ISSUE TITLE
New setup doesn't add entry to hosts automatically

### ISSUE THREAD

**Issue by mwtsn** [kapow-wp/kapow-setup#13]
## Expected Behaviour

*What results were you expecting from the this software?*

I expected the hosts file to be updated with my site url when I provisioned it

## Actual Behaviour

*What actually happened? Please provide as much feedback as possible including error messages*

It did not get added

## Your Specifications

*Share any relevant information about your set-up such as repository version, operating system etc*

My first time using the new build, so could be a training issue.

**Comment by davetgreen** [comment]
@mwtsn the script doesn't add it directly, it relies on Vagrant adding the hosts file after the site has been provisioned. Is that not happening?

**Comment by mwtsn** [comment]
It is not @davetgreen :’(

I’ll play about with it

**Comment by davetgreen** [comment]
@mwtsn hmmm, @nervewax had this issue after he upgraded to Vagrant 2.0, but it didn't affect every domain, just one of them. I'll look into it next week!

**Comment by davetgreen** [comment]
@mwtsn quick question on this sir, when it failed, did you confirm that the script had modified your `vvv-custom.yml` to add the new site entry?

**Comment by davetgreen** [comment]
@mwtsn ping ping ping

**Comment by mwtsn** [comment]
Odd @davetgreen I replied to this via email a bit back.

The script didn’t, I did it manually, but it still didn’t pick it up in hosts.

I’ll be doing a rebuild on a new Mac soon, so perhaps that will fix?

**Comment by davetgreen** [comment]
@mwtsn yeah maybe, we'll leave this open anyways. Still have a feeling it's Vagrant/VVV oddness.

**Comment by davetgreen** [comment]
Closing as determined this was a vvv-custom.yml related issue.
