### ISSUE TITLE
Automatically add labels to repo upon creation

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-setup#18]
Using the GitHub API, automatically delete the repo's labels and populate them with those find in the `labels.json` file.

**Comment by mwtsn** [comment]
@davetgreen here were the suggestions:

PM: Issue (Red)
PM: Risk (Orange)
PM: Decision (White)

Status: In Progress (Grey)
Status: On Hold (Red)
Status: Completed (Green)
Status: Awaiting Feedback (Orange)
Status: Blocked (Red)
Status: Available (Teal)
Status: Awaiting Signoff (Yellow)

Type: Bug (Red)
Type: Enhancement (Orange)
Type: Support (Yellow)
Type: Question (Pink)

Priority: Critical (Red)
Priority: High (Orange)
Priority: Medium (Yellow)
Priority: Low (Green)

Deploy: Pending
Deploy: On Production
Deploy: On Staging

**Comment by davetgreen** [comment]
@mwtsn are we still running with these PM labels given that GitHub is tech people only now?

**Comment by mwtsn** [comment]
Please @davetgreen, it’s handy to patch that gap between the systems.

Regards,

Matt Watson
Make Do

Tel: 07715343287
Web: makedo.net
Twitter: @mwtsn / @makedoers

On 7 Jan 2018, 23:18 +0000, Dave Green <notifications@github.com>, wrote:
> @mwtsn are we still running with these PM labels given that GitHub is tech people only now?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 

MKDO LTD. TRADING AS MAKE DO TM. 
BBIC, INNOVATION WAY, BARNSLEY, S75 1JL, 
UK REGISTERED CO #08453062. VAT #178909059.

**Comment by davetgreen** [comment]
This has now been completed.
