### ISSUE TITLE
Script appears to ignore git parameters in config

### ISSUE THREAD

**Issue by m9n** [kapow-wp/kapow-setup#19]
## Expected Behaviour

*What results were you expecting from the this software?*

In my `kapow.config` I've got the following lines:
```
# Create the repository? (true|false)
setuprepository=false
# Create the default branches? (true|false)
setupbranches=false
```

I would expect the script to read these parameters and act on them.

## Actual Behaviour

*What actually happened? Please provide as much feedback as possible including error messages*

When I run the script, I'm still asked:

```
Config file found! Loading...
Would you like to create a new GitHub repository? (y/n)
```
Then, when I type `n` above, the script still asks me:
```
Success! Your Kapow! instance has now been created.
Would you like to commit and push now? (y|n)
```

**Comment by davetgreen** [comment]
hey @m9n this is a known issue; the kapow.config parameters aren't plumbed into the script yet. It's something that unfortunately isn't documented anywhere. I'm actually working on the script tonight so this should be resolved by the time we're back next week

Closing in favour of #15
