### ISSUE TITLE
Feature: auto import site database

### ISSUE THREAD

**Issue by m9n** [kapow-wp/kapow-setup#25]
**Feature request**

For local development and testing, the Kapow! setup script could install a test database for the project.   The database could reside as a MySQL dump, in a particular folder, with a particular name, included in the repo and could be updated with a fresh dump at any point.

Advantages:
- A rapid start for devs coming in part way through a project, especially where there are features which need some data in for testing and developing.
- Helpful especially for newer or less experienced devs, who are learning lots of systems at once, who just need to run a script to be ready for action.
- Beneficial for more experienced devs working on small retainer: makes project setup trivial, and saves retainer time for more important stuff.

**Comment by davetgreen** [comment]
We used to do this but have moved away from it due to GitHub issues and generally against best practice. Using WPMDB Pro as standard is the preferred mthod.
