### ISSUE TITLE
Issue with grunt script

### ISSUE THREAD

**Issue by mwtsn** [kapow-wp/kapow-setup#27]
## Expected Behaviour

*What results were you expecting from the this software?*

Grunt to work out of the box

## Actual Behaviour

*What actually happened? Please provide as much feedback as possible including error messages*

<img width="956" alt="screen shot 2018-02-26 at 09 06 01" src="https://user-images.githubusercontent.com/2066205/36661797-488c7082-1ad4-11e8-9d0f-057f749d5025.png">

## Your Specifications

*Share any relevant information about your set-up such as repository version, operating system etc*

Wrong path on line 121 of style.scss, has an extra /scss/ in the file path, but correct config is:

<img width="988" alt="screen shot 2018-02-26 at 09 05 23" src="https://user-images.githubusercontent.com/2066205/36661821-620ac8d8-1ad4-11e8-89e3-1f1a981a0dbd.png">

**Comment by davetgreen** [comment]
@mwtsn interesting! It may be that the bower module removed the extra folder, we've had this before with Modernizr etc. I'll patch this morning 👍

**Comment by davetgreen** [comment]
Patched. Actually relates to Kapow! Sass, but patched regardless.

**Comment by davetgreen** [comment]
@mwtsn this has already been patched by Charlie a few weeks ago. 👍

**Comment by mwtsn** [comment]
Hmmm @davetgreen but I pulled it today, so the patch cant have taken?

**Comment by davetgreen** [comment]
@mwtsn I've just patched it manually on master, it musn't have been included in his merge 🤔
