### ISSUE TITLE
Find and replace did not quite work as expected

### ISSUE THREAD

**Issue by mwtsn** [kapow-wp/kapow-setup#28]
## Expected Behaviour

*What results were you expecting from the this software?*

Find and replace to work correctly

## Actual Behaviour

*What actually happened? Please provide as much feedback as possible including error messages*

<img width="503" alt="screen shot 2018-02-26 at 09 02 35" src="https://user-images.githubusercontent.com/2066205/36661864-78b3190a-1ad4-11e8-9c33-4ac9ddf9d6de.png">

hello@makedo.net got changed to hello@thetroop... (the theme name)

## Your Specifications

*Share any relevant information about your set-up such as repository version, operating system etc*

Project name is getting replaced before the email, meaning the email cannot be replaced because it is no longer the same address.

**Comment by davetgreen** [comment]
@mwtsn patched, moved email address above slug.
