### ISSUE TITLE
Following the instructions puts everything in a sub folder

### ISSUE THREAD

**Issue by mwtsn** [kapow-wp/kapow-setup#29]
## Expected Behaviour

*What results were you expecting from the this software?*

After I cd into my project folder, and running the script, I expected all files to be in the root of my project folder

## Actual Behaviour

*What actually happened? Please provide as much feedback as possible including error messages*

Everything was in a sub directory of my project folder

## Your Specifications

*Share any relevant information about your set-up such as repository version, operating system etc*

I may have misunderstood the instructions?

**Comment by davetgreen** [comment]
@mwtsn The set-up script has changed in the last couple of months to actually create the project folder and then `cd` into it, after Mina had a nightmare with the set-up. Expected behaviour, this one.

**Comment by davetgreen** [comment]
Docs need reviewing.

**Comment by davetgreen** [comment]
Edited first point in the instructions, closing off.
