### ISSUE TITLE
Automatically install plugins?

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-setup#36]
We have the opportunity to automatically install plugins via `wp-cli` when the `vvv-init.sh` script runs when the site is provisioned.

This could save us a little bit of time on each build, so I think it's a good idea for us to seriously think about what plugins need to be installed and activated from the get-go.

It's trivial to add these in, we just need to decide what are the plugins that we can't live without. Reply here with ideas and I'll keep the list updated.

- CMB2?
- Imsanity?

**Comment by davetgreen** [comment]
* Regenerate Thumbnails https://en-gb.wordpress.org/plugins/regenerate-thumbnails/

    * Gravity Forms (May need a private repo mirror for this)

    * Imsanity https://wordpress.org/plugins/imsanity/

    * WP Smush Pro???

    * SO Hide SEO Bloat https://en-gb.wordpress.org/plugins/so-clean-up-wp-seo/

    * Yoast SEO https://en-gb.wordpress.org/plugins/wordpress-seo/

    * WP Migrate DB Pro (May need a private repo mirror for this)

    * WP Migrate DB Pro CLI (May need a private repo mirror for this)

    * WP Migrate DB Pro Media Files (May need a private repo mirror for this)

   * WP Mail Catcher ???

**Comment by davetgreen** [comment]
@mattwatsoncodes what do you think of this list of 12 plugins above? ^^

A good head start for development, handy to have on the server(s) as well to be honest.

Can make these happen pretty quick, just 12 lines of `wp cli` goodness!

**Comment by mattwatsoncodes** [comment]
@davetgreen make it so :)
