### ISSUE TITLE
Refactor into new workflow

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-setup#4]
There are a number of optional things that we would ideally want to do upon installing a new Kapow! instance. As a result the script needs to be overhauled to take a more question based approach, similar to the way Gary Jones' plugin deployment script works.

Some discussion is needed around which specific options need to be offered to the user.

**Comment by davetgreen** [comment]
@mwtsn I know we've touched on the kind of things that need to be optionally turned on during the set-up process, can we gather some of these ideas here?

To start with I'm thinking about the JS dependencies in Grunt e.g. do you want select2 to be uncommented and included etc. 

Should we also be looking at including specific plugins/repositories as well? 

An obvious one is what Grunt tasks need to be enabled by default: a couple of the more infrequently used tasks can be disabled by default and only enabled during set-up.

**Comment by mwtsn** [comment]
@davetgreen TBH I think a single config file where you can comment stuff in/out would be easier to manage than a q&a based workflow.

**Comment by davetgreen** [comment]
@mwtsn I'm thinking a `kapow.json` file (or .txt, whatever) containing all the config options. The default settings ship in the repo, and can be tweaked quickly.

**Comment by davetgreen** [comment]
@mwtsn I've started working on a config file for this, so just thinking of things in Kapow that can be turned off and on.

This won't handle things like plugin installation/activation, just general Kapow! instance configs.

Any suggestions?

```
# Enforce WPCS checks via Git pre-commit hooks?
skeleton_precommit_wpcs=true
# Use a front-end framework ? (foundation|bourbon|bootstrap)
sass_framework="noframework"
# Use the Normalize CSS reset?
sass_normalize=true
# Lint PHP, SCSS and Javascript?
grunt_linting=false
```

**Comment by davetgreen** [comment]
All that remains at this stage is to take action to make each of the config options update the relevant string in the instance. I'll do this gradually over the next few days and release this as 2.1.0

**Comment by davetgreen** [comment]
Closing in favour of #15
